# Generated by Django 4.0.3 on 2022-04-04 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_free_advice_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense')], max_length=25, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
